Accept=Onartu
Close=Itxi
Price= Prezioa
SelectOption=Aukeratu
Buy = Erosi
Account=Kontua
Username= Erabiltzaile izena
Salelist=Eskaintza zerrenda
ShowSale=Ikusi eskaintza
Warning=Aukeratu eskaintza


MainGUI.CreateSale= Eskaintza sortu
MainGUI.QuerySales= Eskaintzak kontsultatu
MainGUI.SelectOption=Aukeratu
MainGUI.MainTitle=Merkatua
MainGUI.Login = Saioa Hasi
MainGUI.Register = Erregistratu
MainGUI.Erreklamazioak=Erreklamazioak

CreateSaleGUI.Title=Tituloa
CreateSaleGUI.Description=Deskripzioa
CreateSaleGUI.Status=Egoera
CreateSaleGUI.Category=Kategoria
CreateSaleGUI.Price=Prezioa
CreateSaleGUI.PriceMustBeGreaterThan0=ERROR, prezioa 0 baino handiagoa
CreateSaleGUI.ProductCreated=Eskaintza sortuta
CreateSaleGUI.CreateProduct=Sortu Eskaintza
CreateSaleGUI.ErrorNumber=Error, prezioa zenbaki bat izan behar da
CreateSaleGUI.ErrorQuery=Error, datuak falta dira
CreateSaleGUI.LoadPicture=Argazkia igo
CreateSaleGUI.PublicationDate=Argitarapen eguna

RegisterGUI.Username=Erabiltzaile izena
RegisterGUI.Password=Pasahitza
RegisterGUI.Email=Posta elektronikoa
RegisterGUI.ButtonRegister=Erregistratu

QuerySalesGUI.Search=Bilatu
QuerySalesGUI.NoProducts=Ez daude eskaintzak
QuerySalesGUI.Price=Prezioa
QuerySalesGUI.FindProducts=Eskaintzak bilatu
QuerySalesGUI.Products=Eskaintzak (Double-click eskaintza ikusteko)

ShowSaleGUI.Title=Eskaintza xehestasunak

LoginGUI.name=Izena
LoginGUI.LoginButton=Saioa hasi
LoginGUI.Password=Pasahitza

MugimenduakIkusiGUI.diruaString=Diru Totala
MugimenduakIkusiGUI.getMoney=Dirua Atera
MugimenduakIkusiGUI.setMoney=Dirua Sartu
MugimenduakIkusiGUI.Description=Deskripzioa
MugimenduakIkusiGUI.Money=Dirua
MugimenduakIkusiGUI.Date=Data

ErreklamazioakKudeatuGUI.jarritakoak=Jarritako erreklamazioak
ErreklamazioakKudeatuGUI.jasotakoak=Jasotako erreklamazioak

MainGUI.Mov=Mugimenduak

DataAccess.UserAlreadyExistException=ERROR, e-posta dagoeneko erabilita dago
DataAccess.StringIsEmptyException=ERROR, datu batzuek hutsik daude
DataAccess.SaleAlreadyExist=ERROR, Eskaintza existizen da
DataAccess.ErrorSaleMustBeLaterThanToday=ERROR, data gaur baino beranduago izan behar da
DataAccess.ErrorFileNotUploadedException=ERROR, Argazkia igo behar da
DataAccess.UserOrPasswordIsWrongException=ERROR, izena edo pasahitza gaizki daude
DataAccess.EmailIsNotCorrectException=ERROR, emaila es da egokia
DataAccess.NumberFormatException=ERROR, ez da zenbaki bat
DataAccess.MoneyIsNegativeException=ERROR, dirua negatiboa da
DataAccess.NotEnoughMoneyException=ERROR, ez dago diru nahikorik